<!-- REGRAS PARA NOMES IDENFICADORES -->

<!-- VARIÁVEIS SEMPRE COMEÇAM COM O SÍMBOLO "$" -->
<!-- O SEGUNDO PODE SER LETRA OU O SÍMBOLO "_" -->

<!-- ACEITA CARACTERES [a-z], [A-Z], [0-9] e [_] -->

<!-- ACEITA CARACTERES DA TABELA ASCII A PARTIR DE 128 -->

<!-- ACEITA CARACTERES ACENTUADOS COMO "á", "õ", "ç" -->

<!-- A LINGUAGEM É CASE SENSITIVE EM RELAÇÃO AOS NOMES -->

<!-- NOMES ESPECIAIS COMO "$this" NÃO PODEM SER USADOS -->